# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f387935a6e66cb99216b2a0bc63f38aaaf8e98ec1548b55102df08b94f99228c4dfdc43066f9290d53f349069bcc28bf1865229a17568120d0122d19309d08f

test:
  secret_key_base: 02323784c77b7b8d6b005c4b6e5f950deec40704c988e2f65b1eda5eaff941bea7858f66b172ef378bc3c9004e28340d4518d05315ad692410ff3de1a4f18d6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
